name: testing the input variables

on:
  workflow_dispatch:
    inputs:
      env_input: 
        description: environment name
        required: true
        default: dev
        type: choice
        options:
          - dev
          - tst
          - prd
      tag_name:
        description: tag name
        required: true

jobs:
  test_input_variable:
    name: test input variable
    runs-on: ubuntu-latest
    steps:
      - name: app deploy
        run: echo "deploying app version ${{ inputs.tag_name }} on ${{ inputs.env_input }}"
