name: output demo
on: push
jobs:
  build:
    outputs:
      version: ${{steps.step_id.outputs.version}}
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: step_id
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "print version number = ${{needs.build.outputs.version}}"
